// components/skinai/score-ring.tsx
"use client"

import { cn } from "@/lib/utils"
import { getScoreColor } from "@/lib/skinai-types"
import { useEffect, useState } from "react"

interface ScoreRingProps {
  score: number
  size?: number
  strokeWidth?: number
  animated?: boolean
  className?: string
  showLabel?: boolean
}

export function ScoreRing({
  score,
  size = 120,
  strokeWidth = 8,
  animated = true,
  className,
  showLabel = true,
}: ScoreRingProps) {
  const [displayScore, setDisplayScore] = useState(animated ? 0 : score)
  const [progress, setProgress] = useState(animated ? 0 : score)

  const radius = (size - strokeWidth) / 2
  const circumference = 2 * Math.PI * radius
  const strokeDashoffset = circumference - (progress / 100) * circumference

  useEffect(() => {
    if (!animated) return

    // Animate score number
    const duration = 1000
    const startTime = Date.now()
    const startScore = 0

    const animateScore = () => {
      const elapsed = Date.now() - startTime
      const progress = Math.min(elapsed / duration, 1)
      const easeOut = 1 - Math.pow(1 - progress, 3)
      
      setDisplayScore(Math.round(startScore + (score - startScore) * easeOut))
      setProgress(score * easeOut)

      if (progress < 1) {
        requestAnimationFrame(animateScore)
      }
    }

    requestAnimationFrame(animateScore)
  }, [score, animated])

  return (
    <div className={cn("relative inline-flex items-center justify-center", className)}>
      <svg width={size} height={size} className="-rotate-90">
        {/* Background circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeWidth}
          className="text-muted"
        />
        {/* Progress circle */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={radius}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeWidth}
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={strokeDashoffset}
          className={cn(
            "transition-all duration-1000 ease-out",
            getScoreColor(score)
          )}
        />
      </svg>
      {showLabel && (
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className={cn("text-3xl font-bold", getScoreColor(score))}>
            {displayScore}
          </span>
          <span className="text-xs text-muted-foreground">점</span>
        </div>
      )}
    </div>
  )
}

// frontend/src/components/ScoreRing.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue"
import { scoreColor } from "@/lib/skinai"

const props = withDefaults(defineProps<{
  score: number
  size?: number
  strokeWidth?: number
  animated?: boolean
  showLabel?: boolean
}>(), {
  size: 120,
  strokeWidth: 8,
  animated: true,
  showLabel: true,
})

const displayScore = ref(props.animated ? 0 : props.score)
const progress = ref(props.animated ? 0 : props.score)
const radius = computed(() => (props.size - props.strokeWidth) / 2)
const circumference = computed(() => 2 * Math.PI * radius.value)
const strokeDashoffset = computed(() => circumference.value - (progress.value / 100) * circumference.value)

function animate() {
  if (!props.animated) {
    displayScore.value = props.score
    progress.value = props.score
    return
  }
  const startTime = Date.now()
  const tick = () => {
    const elapsed = Date.now() - startTime
    const amount = Math.min(elapsed / 1000, 1)
    const eased = 1 - Math.pow(1 - amount, 3)
    displayScore.value = Math.round(props.score * eased)
    progress.value = props.score * eased
    if (amount < 1) requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
}

onMounted(animate)
watch(() => props.score, animate)
</script>

<template>
  <div class="relative inline-flex items-center justify-center">
    <svg :width="size" :height="size" class="-rotate-90">
      <circle :cx="size / 2" :cy="size / 2" :r="radius" fill="none" stroke="currentColor" :stroke-width="strokeWidth" class="text-muted" />
      <circle
        :cx="size / 2"
        :cy="size / 2"
        :r="radius"
        fill="none"
        stroke="currentColor"
        :stroke-width="strokeWidth"
        stroke-linecap="round"
        :stroke-dasharray="circumference"
        :stroke-dashoffset="strokeDashoffset"
        :class="['transition-all duration-1000 ease-out', scoreColor(score)]"
      />
    </svg>
    <div v-if="showLabel" class="absolute inset-0 flex flex-col items-center justify-center">
      <span :class="['text-3xl font-bold', scoreColor(score)]">{{ displayScore }}</span>
      <span class="text-xs text-muted-foreground">점</span>
    </div>
  </div>
</template>
